eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
   port: 8902
spring:
   application:
      name: service-feign
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
